# Template for job finder
email: LINKEDIN_EMAIL # Replace with your own email
password: LINKEDIN_PASSWORD # Replace with your own password
params: # Use unique key for each params entry, include as many of these params for each entry as desired
  - SEARCH1:
      keywords: KEYWORD_1 KEYWORD_2
      location: CITY_NAME
      currentJobId: JOB_ID # If looking for specific job (found in URL)
      geoId: GEO_ID # If looking for specific location (found in URL)
  - SEARCH2:
      keywords: KEYWORD_3
      location: CITY_NAME
      currentJobId: JOB_ID # If looking for specific job (found in URL)
      geoId: GEO_ID # If looking for specific location (found in URL)