# Template for scholarship finder
email: GOING_MERRY_EMAIL # Replace with your own email
password: GOING_MERRY_PASSWORD # Replace with your own password
params: # Include as many of these params for each entry as desired; careful with indentation
    # The following params are highly recommended to find relevant scholarships
    - eg: mat # Only display scholarships with high match for eligibility
      hide: COS # Hide college-specific scholarships